version: '2'

services:
  php:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/var/www
    working_dir: /var/www
    links:
      - rabbit

  rabbit:
    image: rabbitmq:3.7
    ports:
      - 5672:5672